FROM panoptix/gitblit

MAINTAINER Stephan Buys <stephan.buys@panoptix.co.za>

ADD gitblit.properties /opt/gitblit-data/gitblit.properties
ADD jenkins.groovy /opt/gitblit-data/groovy/jenkins.groovy
# ADD hotrod-composition.git /opt/gitblit-data/git/hotrod-composition.git
# ADD site /opt/gitblit-data/git/site
