# .buildkite/pipeline.yml

env:
  THIS_WILL_APPLY_TO_ALL: true

steps:
  - name: "Build Docker Machine"
    command: "./test/run_ci_build.sh"
    concurrency: 1
    concurrency_group: dockerbuild

  - waiter

  - name: "Remove stale apps"
    command: "rm -rf ./local/*"

  - waiter

  - name: "Seed the project and default files"
    command: "./test/run_ci_seed.sh"

  - waiter

  - name: "Run Template Engine"
    command: "mini.py"
    
  - waiter
  
  - name: "Install HotRod Apps"
    command: "bash ./bin/install_apps.sh"

  - waiter

  - name: "HotRod Init"
    command: "./test/run_ci_init.sh"

  - waiter

  - name: "Run Tests"
    command: "./test/run_tests.sh"
  
  - waiter

  - name: "Destroy Docker Machine"
    command: "./test/destroy_ci_build.sh"
    
