FROM panoptix/hotrod-auth

MAINTAINER Stephan Buys <stephan.buys@panoptix.co.za>

ADD local.yml /usr/src/app/src/config/local.yml


# To build (from this folder):
# docker build -t hotrod-auth .
# docker run -d -p 3001:3001 --name hotrod-auth-test hotrod-auth
