#!/bin/sh
set -e

#Inspired by https://github.com/zettio/weave

usage() {
    echo "Usage:"
    echo ""
    echo "hotrodctl start"
    echo "hotrodctl stop"    
    echo "hotrodctl status"        
    echo "hotrodctl update"
    echo "hotrodctl project-setup"
    echo ""
    exit 1
}

[ $# -gt 0 ] || usage

COMMAND=$1

shift 1

startcore() {
  /usr/local/bin/start_corehotrod.sh  
  /usr/local/bin/network_corehotrod.sh    
}

startother() {
  if [ -f /usr/local/bin/start_hotrod.sh ]; then 
    /usr/local/bin/start_hotrod.sh
    /usr/local/bin/network_hotrod.sh  
  else
    echo "Starting hotrod containers using 'update'"
    update
  fi
}

quickstart() {
  startcore
  startother
}

projtop() {
  CID=$(docker ps | grep core | grep saltmaster | cut -f1 -d" ")
  docker exec $CID /usr/bin/salt-run fileserver.update
  docker exec $CID /usr/bin/salt \* -t 600 state.highstate
  
}

status() {
  docker ps | grep hotrod
}

update() {
  echo "Build, Run, Network... (please wait)"
  CID=$(docker ps | grep core | grep saltmaster | cut -f1 -d" ")
  docker exec $CID /usr/bin/salt-run fileserver.update
  docker exec $CID /usr/bin/salt \* -t 600 state.sls cluster.build
  docker exec $CID /usr/bin/salt \* -t 600 state.sls cluster.run
  docker exec $CID /usr/bin/salt \* -t 600 state.sls cluster.network
  echo ""
  echo "Build, Run, Network... (DONE)"
}

case "$COMMAND" in
    start)
        quickstart
        ;;
    stop)
      docker stop $(docker ps | grep hotrod | cut -f1 -d" ")
      ;;
    update)
        update
        ;;
    project-setup)
        projtop
        ;;      
    status)
        status
        ;;
    start-core)
        startcore
        ;;
    start-proj)
        startother
        ;;
        
    *)
        echo "Unknown hotrod command '$COMMAND'" >&2
        usage
        ;;
esac        
