FROM panoptix/hotrod-jwt-proxy:latest

MAINTAINER Stephan Buys <stephan.buys@panoptix.co.za>

ADD local.yml /usr/src/app/src/config/local.yml


# To build (from this folder):
# docker build -t hotrod-jwt-proxy .
# docker run -p 4000:4000 -d --name hotrod-jwt-proxy-test hotrod-jwt-proxy
